language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
services:
  - memcached
before_install:
  - env | sort
  - sudo apt-get install libcloog-ppl0
  - cpanm --verbose --installdeps --notest . || echo failed
