#!/bin/sh -e
#
# This directory contains the source code for libmemcached that we will build and link to.
# 
# In future it may also contain source to memcached so we can be sure to have one available for running tests.
#
# TO UPGRADE TO A NEW libmemcached RELEASE:
#
#   ./README 0.45
#
v=${1?Specify the version to use as an argument, e.g., 0.45}
rm -f libmemcached-$v.tar.gz
wget http://launchpad.net/libmemcached/1.0/$v/+download/libmemcached-$v.tar.gz
tar xfz libmemcached-$v.tar.gz
rm -rf libmemcached-prev
mv libmemcached libmemcached-prev
mv libmemcached-$v libmemcached
git add libmemcached
(cd .. && perl -MExtUtils::Manifest=mkmanifest -e mkmanifest)
